### ISSUE TITLE
Load schema from file appears to do nothing

### ISSUE THREAD

**Issue by zildac** [FWDSEC/burp-auto-gql#11]
Hi,

As per title, selecting a valid JSON formatted schema and populating the http endpoint appears to do nothing when pressing "Get all available queries". Have verified the schema is imported successfully using the inQL extension.

**Comment by jmeit-fwdsec** [comment]
Hi @zildac ,

You need to also supply a GraphQL Endpoint URL, because it's not just listing the queries, but also preparing the HTTP requests. I need to update the instructions. Let me know if that works for you. If you use the Logger++ extension you can see that no request actually gets made to the GraphQL endpoint as long as you provide a valid schema file. 

If it's still not working for you, we may have to dig into the schema file itself to find the bug, if you're ok sharing it.

Let me know.

**Comment by zildac** [comment]
Hey,

Thanks for the quick response. I did supply the endpoint, it doesn't have introspection enabled. Happy to share the JSON schema privately.  Will check the Logger++ output tomorrow.

**Comment by jmeit-fwdsec** [comment]
Sounds good. Let me know after you check Logger++. You can send the schema to me by email if you prefer at [j.meit@fwdsec.com](mailto:j.meit@fwdsec.com).

**Comment by zildac** [comment]
Hi Jared,

Still no joy I'm afraid. Both the endpoint and schema field are populated,
but "Get all possible queries" returns nothing :-(

Schema attached....

Regards,

Ross.

**Comment by zildac** [comment]
> Sounds good. Let me know after you check Logger++. You can send the schema to me by email if you prefer at [j.meit@fwdsec.com](mailto:j.meit@fwdsec.com).

Mail sent 👍

**Comment by jmeit-fwdsec** [comment]
Thanks for sending it. Turns out the issue was with the schema file. It was missing the "data" property which is normally returned from introspection queries. This is also how https://graphql-kit.com/graphql-voyager/ requires the introspection data, which helped me debug this.

The json should have started with
```
{
  "data":
```
with an extra `}` at the bottom of the file to close it off.

But since some tools will export the schema without the `data` property, I'm going to add the ability to read schema files like that with the incoming commit. By the time you read this it should be fixed. So you can pull the latest code once you see this issue closed, or wrap the `__schema` field with the `data` property.

**Comment by zildac** [comment]
Fantastic! Much appreciated!
